#
# Copyright 2012-2019 CNRS-UM LIRMM, CNRS-AIST JRL
#

dist: xenial
addons:
  apt:
    packages:
    - doxygen
    - doxygen-latex
    - libboost-all-dev
    - libeigen3-dev
    - python-pip
    - python3-pip
    - cython
    - python-nose
    - python-numpy
    - python-coverage
    - cython3
    - python3-nose
    - python3-numpy
    - python3-coverage
    - python3-setuptools
branches:
  except:
    - debian
language: cpp
compiler:
- gcc
- clang
env:
  global:
  - APT_DEPENDENCIES=""
  - GIT_DEPENDENCIES="jrl-umi3218/Eigen3ToPython"
  - GH_USERNAME=gergondet
  - GH_REPO=jrl-umi3218/SpaceVecAlg
  - secure: FWu5+09qN8j8CF6ecpX81eX/gC6QkmXcps3jHyHfhggoKHXLIGL1qN6bICXgjVzhpJbmmAEEJUtbN5UMOSPnJ/kInVR36eR1VwUAQUL81PJazH5XVDgznF8shontCbow6lG0WQ9xCZzVfW77V9DXv4QL5K2tfOtRmStbtUiTdf4ZUs=
  - CMAKE_ADDITIONAL_OPTIONS="-DPYTHON_BINDING_BUILD_PYTHON2_AND_PYTHON3:BOOL=ON -DPYTHON_BINDING_USER_INSTALL:BOOL=ON"
notifications:
  slack:
    secure: gCrurakYrdf1A2VxY3eDotv2JGfXQd07ELV3vKoBXBEu3bmv5qfwrqV05FSkZG6rK/O55DRC6KkIftGu79Tk+gCD+iPMXJtKMcdMaEPeO17jB/vPTWHtpGLnC0FevyqQGq0AfGAPjRbUEs1dB9WKBVPCu1KUmnl7sODe3WFYBPs=
before_install: ./.travis/run  before_install
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
